services:

  reniec-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: reniec-api

    restart: unless-stopped

    environment:
      APP_NAME: "RENIEC API"
      APP_ENV: "production"
      APP_HOST: "0.0.0.0"
      APP_PORT: "8000"

      DB_HOST: "192.168.0.107"
      DB_PORT: "6543"
      DB_NAME: "rec"
      DB_USER: "admin"
      DB_PASSWORD: "${DB_PASSWORD}"

      DB_MIN_POOL: "1"
      DB_MAX_POOL: "10"

      KEYCLOAK_URL: "https://auth.fama.net.pe"
      KEYCLOAK_REALM: "reniec"
      KEYCLOAK_AUDIENCE: "reniec-api"
      KEYCLOAK_ALLOWED_USERNAME: "hard"

    ports:
      - "8001:8000"
